name: Deploy App

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-latest

  steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: "18"

    - name: Build App
      run: npm ci
      run: npm run build.server

    - name: Setup Pages
      uses: actions/configure-pages@v3

    - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './dist'
          
    - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2